# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 3.5
      - python: 3.6
      
install:
  - pip install pytest dask distributed

script:
  - pip install .
  - pytest -vrsx
