# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 3.5
      - python: 3.6
      
install:
  - pip install pytest dask distributed
  - pip install --upgade git+https://github.com/cloudpipe/cloudpickle@master

script:
  - pip install .
  - pytest -vrsx
